/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as RbacRouteImport } from './routes/rbac'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as StudyAbroadIndexRouteImport } from './routes/study-abroad.index'
import { Route as StudyAbroadSlugRouteImport } from './routes/study-abroad.$slug'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardBlogRouteImport } from './routes/_authenticated/dashboard.blog'
import { Route as AuthenticatedDashboardMediaRouteImport } from './routes/_authenticated/dashboard.media'
import { Route as AuthenticatedDashboardMessagesRouteImport } from './routes/_authenticated/dashboard.messages'
import { Route as AuthenticatedDashboardReviewsRouteImport } from './routes/_authenticated/dashboard.reviews'
import { Route as AuthenticatedDashboardServicesRouteImport } from './routes/_authenticated/dashboard.services'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardStudyAbroadRouteImport } from './routes/_authenticated/dashboard.study-abroad'
import { Route as AuthenticatedDashboardTestimonialsRouteImport } from './routes/_authenticated/dashboard.testimonials'
import { Route as AuthenticatedDashboardToursRouteImport } from './routes/_authenticated/dashboard.tours'
import { Route as AuthenticatedDashboardUniversitiesRouteImport } from './routes/_authenticated/dashboard.universities'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const RbacRoute = RbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadIndexRoute = StudyAbroadIndexRouteImport.update({
  id: '/study-abroad/',
  path: '/study-abroad/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadSlugRoute = StudyAbroadSlugRouteImport.update({
  id: '/study-abroad/$slug',
  path: '/study-abroad/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/tours/$slug',
  path: '/tours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBlogRoute =
  AuthenticatedDashboardBlogRouteImport.update({
    id: '/blog',
    path: '/blog',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMediaRoute =
  AuthenticatedDashboardMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMessagesRoute =
  AuthenticatedDashboardMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReviewsRoute =
  AuthenticatedDashboardReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardServicesRoute =
  AuthenticatedDashboardServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStudyAbroadRoute =
  AuthenticatedDashboardStudyAbroadRouteImport.update({
    id: '/study-abroad',
    path: '/study-abroad',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTestimonialsRoute =
  AuthenticatedDashboardTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardToursRoute =
  AuthenticatedDashboardToursRouteImport.update({
    id: '/tours',
    path: '/tours',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUniversitiesRoute =
  AuthenticatedDashboardUniversitiesRouteImport.update({
    id: '/universities',
    path: '/universities',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/rbac': typeof RbacRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/study-abroad/$slug': typeof StudyAbroadSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/study-abroad/': typeof StudyAbroadIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/dashboard/blog': typeof AuthenticatedDashboardBlogRoute
  '/dashboard/media': typeof AuthenticatedDashboardMediaRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard/services': typeof AuthenticatedDashboardServicesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/study-abroad': typeof AuthenticatedDashboardStudyAbroadRoute
  '/dashboard/testimonials': typeof AuthenticatedDashboardTestimonialsRoute
  '/dashboard/tours': typeof AuthenticatedDashboardToursRoute
  '/dashboard/universities': typeof AuthenticatedDashboardUniversitiesRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/rbac': typeof RbacRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/study-abroad/$slug': typeof StudyAbroadSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/services': typeof ServicesIndexRoute
  '/study-abroad': typeof StudyAbroadIndexRoute
  '/tours': typeof ToursIndexRoute
  '/dashboard/blog': typeof AuthenticatedDashboardBlogRoute
  '/dashboard/media': typeof AuthenticatedDashboardMediaRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard/services': typeof AuthenticatedDashboardServicesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/study-abroad': typeof AuthenticatedDashboardStudyAbroadRoute
  '/dashboard/testimonials': typeof AuthenticatedDashboardTestimonialsRoute
  '/dashboard/tours': typeof AuthenticatedDashboardToursRoute
  '/dashboard/universities': typeof AuthenticatedDashboardUniversitiesRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/rbac': typeof RbacRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/study-abroad/$slug': typeof StudyAbroadSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/study-abroad/': typeof StudyAbroadIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/_authenticated/dashboard/blog': typeof AuthenticatedDashboardBlogRoute
  '/_authenticated/dashboard/media': typeof AuthenticatedDashboardMediaRoute
  '/_authenticated/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/_authenticated/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/_authenticated/dashboard/services': typeof AuthenticatedDashboardServicesRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/study-abroad': typeof AuthenticatedDashboardStudyAbroadRoute
  '/_authenticated/dashboard/testimonials': typeof AuthenticatedDashboardTestimonialsRoute
  '/_authenticated/dashboard/tours': typeof AuthenticatedDashboardToursRoute
  '/_authenticated/dashboard/universities': typeof AuthenticatedDashboardUniversitiesRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/rbac'
    | '/dashboard'
    | '/services/$slug'
    | '/study-abroad/$slug'
    | '/tours/$slug'
    | '/services/'
    | '/study-abroad/'
    | '/tours/'
    | '/dashboard/blog'
    | '/dashboard/media'
    | '/dashboard/messages'
    | '/dashboard/reviews'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/study-abroad'
    | '/dashboard/testimonials'
    | '/dashboard/tours'
    | '/dashboard/universities'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/rbac'
    | '/services/$slug'
    | '/study-abroad/$slug'
    | '/tours/$slug'
    | '/services'
    | '/study-abroad'
    | '/tours'
    | '/dashboard/blog'
    | '/dashboard/media'
    | '/dashboard/messages'
    | '/dashboard/reviews'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/study-abroad'
    | '/dashboard/testimonials'
    | '/dashboard/tours'
    | '/dashboard/universities'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/rbac'
    | '/_authenticated/dashboard'
    | '/services/$slug'
    | '/study-abroad/$slug'
    | '/tours/$slug'
    | '/services/'
    | '/study-abroad/'
    | '/tours/'
    | '/_authenticated/dashboard/blog'
    | '/_authenticated/dashboard/media'
    | '/_authenticated/dashboard/messages'
    | '/_authenticated/dashboard/reviews'
    | '/_authenticated/dashboard/services'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/study-abroad'
    | '/_authenticated/dashboard/testimonials'
    | '/_authenticated/dashboard/tours'
    | '/_authenticated/dashboard/universities'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  RbacRoute: typeof RbacRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  StudyAbroadSlugRoute: typeof StudyAbroadSlugRoute
  ToursSlugRoute: typeof ToursSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  StudyAbroadIndexRoute: typeof StudyAbroadIndexRoute
  ToursIndexRoute: typeof ToursIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rbac': {
      id: '/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof RbacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad/': {
      id: '/study-abroad/'
      path: '/study-abroad'
      fullPath: '/study-abroad/'
      preLoaderRoute: typeof StudyAbroadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad/$slug': {
      id: '/study-abroad/$slug'
      path: '/study-abroad/$slug'
      fullPath: '/study-abroad/$slug'
      preLoaderRoute: typeof StudyAbroadSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/tours'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/tours/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/blog': {
      id: '/_authenticated/dashboard/blog'
      path: '/blog'
      fullPath: '/dashboard/blog'
      preLoaderRoute: typeof AuthenticatedDashboardBlogRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/media': {
      id: '/_authenticated/dashboard/media'
      path: '/media'
      fullPath: '/dashboard/media'
      preLoaderRoute: typeof AuthenticatedDashboardMediaRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/messages': {
      id: '/_authenticated/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reviews': {
      id: '/_authenticated/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof AuthenticatedDashboardReviewsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/services': {
      id: '/_authenticated/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof AuthenticatedDashboardServicesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/study-abroad': {
      id: '/_authenticated/dashboard/study-abroad'
      path: '/study-abroad'
      fullPath: '/dashboard/study-abroad'
      preLoaderRoute: typeof AuthenticatedDashboardStudyAbroadRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/testimonials': {
      id: '/_authenticated/dashboard/testimonials'
      path: '/testimonials'
      fullPath: '/dashboard/testimonials'
      preLoaderRoute: typeof AuthenticatedDashboardTestimonialsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tours': {
      id: '/_authenticated/dashboard/tours'
      path: '/tours'
      fullPath: '/dashboard/tours'
      preLoaderRoute: typeof AuthenticatedDashboardToursRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/universities': {
      id: '/_authenticated/dashboard/universities'
      path: '/universities'
      fullPath: '/dashboard/universities'
      preLoaderRoute: typeof AuthenticatedDashboardUniversitiesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBlogRoute: typeof AuthenticatedDashboardBlogRoute
  AuthenticatedDashboardMediaRoute: typeof AuthenticatedDashboardMediaRoute
  AuthenticatedDashboardMessagesRoute: typeof AuthenticatedDashboardMessagesRoute
  AuthenticatedDashboardReviewsRoute: typeof AuthenticatedDashboardReviewsRoute
  AuthenticatedDashboardServicesRoute: typeof AuthenticatedDashboardServicesRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardStudyAbroadRoute: typeof AuthenticatedDashboardStudyAbroadRoute
  AuthenticatedDashboardTestimonialsRoute: typeof AuthenticatedDashboardTestimonialsRoute
  AuthenticatedDashboardToursRoute: typeof AuthenticatedDashboardToursRoute
  AuthenticatedDashboardUniversitiesRoute: typeof AuthenticatedDashboardUniversitiesRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBlogRoute: AuthenticatedDashboardBlogRoute,
    AuthenticatedDashboardMediaRoute: AuthenticatedDashboardMediaRoute,
    AuthenticatedDashboardMessagesRoute: AuthenticatedDashboardMessagesRoute,
    AuthenticatedDashboardReviewsRoute: AuthenticatedDashboardReviewsRoute,
    AuthenticatedDashboardServicesRoute: AuthenticatedDashboardServicesRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardStudyAbroadRoute:
      AuthenticatedDashboardStudyAbroadRoute,
    AuthenticatedDashboardTestimonialsRoute:
      AuthenticatedDashboardTestimonialsRoute,
    AuthenticatedDashboardToursRoute: AuthenticatedDashboardToursRoute,
    AuthenticatedDashboardUniversitiesRoute:
      AuthenticatedDashboardUniversitiesRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  RbacRoute: RbacRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  StudyAbroadSlugRoute: StudyAbroadSlugRoute,
  ToursSlugRoute: ToursSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  StudyAbroadIndexRoute: StudyAbroadIndexRoute,
  ToursIndexRoute: ToursIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
