INSERT INTO public.promotions (title, subtitle, description, featured_image, placement, sort_order, status) VALUES
('Turkey Zero Study Package', 'Study & Work Visa', 'Turkish language course package with admission in 48hrs and visa processing in 4 weeks. 2026 July/September intake.', '/__l5e/assets-v1/1d6aa7c0-be64-42cf-9d08-ad8803ca3f85/flyer-turkey-study-package.jpeg', 'homepage', 1, 'published'),
('Oman 2-Year Freelance Work Visa', 'Payment After Visa Approval', '24hrs / 72hrs processing. Package includes visa, medical & ID, job connection, airport pickup, flight ticket and accommodation.', '/__l5e/assets-v1/b817f053-cc4e-4184-905c-c323b66ebe5f/flyer-oman-work-visa.jpeg', 'homepage', 2, 'published'),
('Qatar 2-Year Freelance Work Visa', 'Live & Work in Qatar', 'Work opportunities across Qatar with relocation support, accommodation and full job search assistance.', '/__l5e/assets-v1/48199825-1337-4839-9c4b-d9af3beb7863/flyer-qatar-work-visa.jpeg', 'homepage', 3, 'published'),
('Kuwait 2-Year Direct Employment', 'Warehouse Positions', 'Salary 120KWD - 180KWD with accommodation, work ID, airport pickup and work uniform included. Limited slots.', '/__l5e/assets-v1/e29d6419-6976-4ab3-8a35-b08ce301b1b5/flyer-kuwait-work-visa.jpeg', 'homepage', 4, 'published');

INSERT INTO public.testimonials (title, slug, client_name, service_used, country, content, rating, featured_image, sort_order, status) VALUES
('Another success story', 'success-story-departure', NULL, 'Travel & Visa Assistance', NULL, 'Another client cleared for departure with Brilliant Mind Travels & Tours.', 5, '/__l5e/assets-v1/496d7367-569c-47c7-9a04-4bfe01963733/success-story-departure.jpeg', 1, 'published'),
('Clients checked in for departure', 'clients-checked-in-departure', NULL, 'Travel & Visa Assistance', NULL, 'Our clients at the airport, fully documented and on their way abroad.', 5, '/__l5e/assets-v1/08eb3cad-4964-41de-ac69-d948fbcdf009/travellers-airport-1.jpeg', 2, 'published'),
('Group departure at International Departures', 'group-international-departures', NULL, 'Work Visa Processing', NULL, 'A group of clients successfully processed and departing together.', 5, '/__l5e/assets-v1/79b609f7-a6af-4c98-a9c4-a30e13514a2e/travellers-departures-2.jpeg', 3, 'published'),
('Visa approved and collected', 'visa-approved-collected', NULL, 'Visa Processing', NULL, 'Approved visa collected by a happy client.', 5, '/__l5e/assets-v1/729e9696-537a-4128-b72d-1bcbd1695606/visa-approval-proof.jpeg', 4, 'published');